### ISSUE TITLE
Failed to compile with 7 errors

### ISSUE THREAD

**Issue by aryan-jadon** [minutelabsio/evolution-simulator#10]
**Copilot Error along with icons**

These dependencies were not found:

* copilot in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/view-screen.vue?vue&type=script&lang=js& and 4 others
* @/assets/status-icons/extinction.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"b789fb22-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/pug-plain-loader!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/simulation.vue?vue&type=template&id=3a6177ea&scoped=true&lang=pug&

To install them, you can run: npm install --save copilot @/assets/status-icons/extinction.svg

**Comment by rkraneis** [comment]
Seems the author is using a case insensitive file system. The file is actually called Extinction.svg and should be renamed to lower case extinction.svg.

**Comment by inklinsworld** [comment]
k
